# network/docker-compose.yaml

version: "2"

services:
  orderer.example.com:
    image: hyperledger/fabric-orderer:latest
    environment:
      - FABRIC_LOGGING_SPEC=INFO
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_GENESISMETHOD=file
      - ORDERER_GENERAL_GENESISFILE=/var/hyperledger/orderer/orderer.genesis.block
      - ORDERER_GENERAL_LOCALMSPID=OrdererMSP
      - ORDERER_GENERAL_LOCALMSPDIR=/var/hyperledger/orderer/msp
      - CORE_CHAINCODE_EXECUTETIMEOUT=600s
      - GRPC_MAX_RECEIVE_MESSAGE_LENGTH=314572800
      - GRPC_MAX_SEND_MESSAGE_LENGTH=314572800
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/orderer
    command: orderer
    volumes:
      - ./channel-artifacts/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
      - ./crypto-config/ordererOrganizations/example.com/orderers/orderer.example.com/msp:/var/hyperledger/orderer/msp
    ports:
      - 7050:7050

  peer0.hartley.example.com:
    image: hyperledger/fabric-peer:latest
    environment:
      - FABRIC_LOGGING_SPEC=INFO
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_PEER_ID=peer0.hartley.example.com
      - CORE_PEER_ADDRESS=peer0.hartley.example.com:7051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:7051
      - CORE_PEER_CHAINCODEADDRESS=peer0.hartley.example.com:7052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:7052
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.hartley.example.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.hartley.example.com:7051
      - CORE_PEER_LOCALMSPID=HartleyMSP
      - CORE_VM_DOCKER_ATTACHSTDOUT=true
      - CORE_PEER_MSPCONFIGPATH=/var/hyperledger/peer/msp
      - CORE_CHAINCODE_EXECUTETIMEOUT=600s
      - GRPC_MAX_RECEIVE_MESSAGE_LENGTH=314572800
      - GRPC_MAX_SEND_MESSAGE_LENGTH=314572800
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: peer node start
    volumes:
      - /var/run/docker.sock:/host/var/run/docker.sock
      - ./crypto-config/peerOrganizations/hartley.example.com/peers/peer0.hartley.example.com/msp:/var/hyperledger/peer/msp
    ports:
      - 7051:7051
      - 7052:7052
