---
Organizations:
  - &OrdererOrg
    Name: OrdererOrg
    ID: OrdererMSP
    MSPDir: /Users/joe/hartley-fabric/network/crypto-config/ordererOrganizations/hartley.example.com/msp
    Policies:
      Readers:
        Type: Signature
        Rule: "OR('OrdererMSP.admin')"
      Writers:
        Type: Signature
        Rule: "OR('OrdererMSP.admin')"
      Admins:
        Type: Signature
        Rule: "OR('OrdererMSP.admin')"
      OrdererAdmins:
        Type: Signature
        Rule: "OR('OrdererMSP.admin')"

  - &HartleyMSP
    Name: HartleyMSP
    ID: HartleyMSPID
    MSPDir: /Users/joe/hartley-fabric/network/crypto-config/peerOrganizations/hartley.example.com/msp
    Policies:
      Readers:
        Type: Signature
        Rule: "OR('HartleyMSPID.admin', 'HartleyMSPID.peer', 'HartleyMSPID.client')"
      Writers:
        Type: Signature
        Rule: "OR('HartleyMSPID.admin', 'HartleyMSPID.client')"
      Admins:
        Type: Signature
        Rule: "OR('HartleyMSPID.admin')"
      Endorsement:
        Type: Signature
        Rule: "OR('HartleyMSPID.peer')"

Capabilities:
  Channel: &ChannelCapabilities
    V2_0: true
  Orderer: &OrdererCapabilities
    V2_0: true
  Application: &ApplicationCapabilities
    V2_0: true

Orderer: &OrdererDefaults
  OrdererType: solo
  Addresses:
    - orderer.hartley.example.com:7050
  BatchTimeout: 2s
  BatchSize:
    MaxMessageCount: 10
    AbsoluteMaxBytes: 99 MB
    PreferredMaxBytes: 512 KB
  Organizations:
  Policies:
    Readers:
      Type: ImplicitMeta
      Rule: "ANY Readers"
    Writers:
      Type: ImplicitMeta
      Rule: "ANY Writers"
    Admins:
      Type: ImplicitMeta
      Rule: "MAJORITY Admins"
    BlockValidation:
      Type: ImplicitMeta
      Rule: "ANY Writers"

Channel: &ChannelDefaults
  Policies:
    Readers:
      Type: ImplicitMeta
      Rule: "ANY Readers"
    Writers:
      Type: ImplicitMeta
      Rule: "ANY Writers"
    Admins:
      Type: ImplicitMeta
      Rule: "MAJORITY Admins"
  Capabilities:
    <<: *ChannelCapabilities

Application: &ApplicationDefaults
  Organizations:
  Policies:
    Readers:
      Type: ImplicitMeta
      Rule: "ANY Readers"
    Writers:
      Type: ImplicitMeta
      Rule: "ANY Writers"
    Admins:
      Type: ImplicitMeta
      Rule: "MAJORITY Admins"
    LifecycleEndorsement:
      Type: ImplicitMeta
      Rule: "MAJORITY Endorsement"
    Endorsement:
      Type: ImplicitMeta
      Rule: "MAJORITY Endorsement"
  Capabilities:
    <<: *ApplicationCapabilities

Profiles:
  HartleyGenesis:
    <<: *ChannelDefaults
    Capabilities:
      <<: *ChannelCapabilities
    Orderer:
      <<: *OrdererDefaults
      Organizations:
        - *OrdererOrg
    Consortiums:
      SampleConsortium:
        Organizations:
          - *HartleyMSP
    Application:
      <<: *ApplicationDefaults
      Organizations:
        - *HartleyMSP
      Capabilities:
        <<: *ApplicationCapabilities

  HartleyChannel:
    Consortium: SampleConsortium
    <<: *ChannelDefaults
    Capabilities:
      <<: *ChannelCapabilities
    Application:
      <<: *ApplicationDefaults
      Organizations:
        - *HartleyMSP
      Capabilities:
        <<: *ApplicationCapabilities
    Orderer:
      <<: *OrdererDefaults
      Organizations:
        - *OrdererOrg
      Capabilities:
        <<: *OrdererCapabilities
      Policies:
        Readers:
          Type: ImplicitMeta
          Rule: "ANY Readers"
        Writers:
          Type: ImplicitMeta
          Rule: "ANY Writers"
        Admins:
          Type: ImplicitMeta
          Rule: "MAJORITY Admins"
        BlockValidation:
          Type: ImplicitMeta
          Rule: "ANY Writers"
    Consortiums:
      SampleConsortium:
        Organizations:
          - *HartleyMSP
