peer:
  id: myPeer
  networkId: mynetwork
  listenAddress: 0.0.0.0:7051
  chaincodeListenAddress: 0.0.0.0:7052
  gomaxprocs: -1
  keepalive:
    minInterval: 60s
    client:
      interval: 60s
      timeout: 20s
    deliveryClient:
      interval: 60s
      timeout: 20s
  gossip:
    useLeaderElection: true
    orgLeader: false
    membershipTrackerInterval: 5s
    maxBlockCountToStore: 100
    maxPropagationBurstLatency: 10ms
    maxPropagationBurstSize: 10
    propagateIterations: 1
    propagatePeerNum: 3
    pullInterval: 4s
    pullPeerNum: 3
    requestStateInfoInterval: 4s
    publishStateInfoInterval: 4s
    stateInfoRetentionInterval: 0s
    publishCertPeriod: 10s
    skipBlockVerification: false
    dialTimeout: 3s
    connTimeout: 2s
    recvBuffSize: 20
    sendBuffSize: 200
    digestWaitTime: 1s
    requestWaitTime: 1500ms
    responseWaitTime: 2s
    aliveTimeInterval: 5s
    aliveExpirationTimeout: 25s
    reconnectInterval: 25s
    externalEndpoint: ""
    election:
      startupGracePeriod: 15s
      membershipSampleInterval: 1s
      leaderAliveThreshold: 10s
      leaderElectionDuration: 5s
  events:
    address: 0.0.0.0:7053
    buffersize: 100
    timeout: 10ms
    timewindow: 15m
    keepalive:
      minInterval: 60s
    tls:
      enabled: false
      clientAuthRequired: false
      cert:
        file: /Users/joe/hartley-fabric/network/crypto-config/peerOrganizations/hartley.example.com/peers/peer0.hartley.example.com/tls/server.crt
      key:
        file: /Users/joe/hartley-fabric/network/crypto-config/peerOrganizations/hartley.example.com/peers/peer0.hartley.example.com/tls/server.key
      rootcert:
        file: /Users/joe/hartley-fabric/network/crypto-config/peerOrganizations/hartley.example.com/peers/peer0.hartley.example.com/tls/ca.crt
      clientRootCAs:
        files:
          - /Users/joe/hartley-fabric/network/crypto-config/peerOrganizations/hartley.example.com/peers/peer0.hartley.example.com/tls/ca.crt
  authentication:
    timewindow: 15m
  fileSystemPath: /var/hyperledger/production
  BCCSP:
    Default: SW
    SW:
      Hash: SHA2
      Security: 256
      FileKeyStore:
        KeyStore: msp/keystore
  mspConfigPath: /Users/joe/hartley-fabric/network/crypto-config/peerOrganizations/hartley.example.com/users/Admin@hartley.example.com/msp
  localMspId: HartleyMSPID
  deliveryclient:
    reconnectTotalTimeThreshold: 3600s
  localMspType: bccsp
  profile:
    enabled: false
    listenAddress: 0.0.0.0:6060
  adminService:
    listenAddress: 0.0.0.0:7055
  handlers:
    authFilters:
      - name: DefaultAuth
      - name: ExpirationCheck
    decorators:
      - name: DefaultDecorator
    endorsers:
      escc:
        name: DefaultEndorsement
    validators:
      vscc:
        name: DefaultValidation
  validatorPoolSize: 8
  discovery:
    enabled: true
    authCacheEnabled: true
    authCacheMaxSize: 1000
    authCacheTTL: 10m
    orgMembersAllowedAccess: false

chaincode:
  builder: $(DOCKER_NS)/fabric-ccenv:$(ARCH)-$(PROJECT_VERSION)
  pull: false
  golang:
    runtime: $(DOCKER_NS)/fabric-baseos:$(ARCH)-$(PROJECT_VERSION)
    dynamicLink: false
  car:
    runtime: $(DOCKER_NS)/fabric-baseos:$(ARCH)-$(PROJECT_VERSION)
  java:
    runtime: $(DOCKER_NS)/fabric-javaenv:$(ARCH)-$(PROJECT_VERSION)
  node:
    runtime: $(DOCKER_NS)/fabric-nodeenv:$(ARCH)-$(PROJECT_VERSION)
  startuptimeout: 300s
  executetimeout: 30s
  mode: net
  keepalive: 0
  system:
    cscc: enable
    lscc: enable
    qscc: enable
    vscc: enable
  logging:
    level: info
    shim: warning
    format: "%{color}%{time:2006-01-02 15:04:05.000 MST} %{id:03x} %{color:reset} %{message}"
  externalBuilders: []
  systemPlugins: []
  userRunsCC: false

ledger:
  blockchain:
    leveldb:
      noiteratorcounters: true
  history:
    enableHistoryDatabase: true
  state:
    stateDatabase: goleveldb
    couchDBConfig:
      couchDBAddress: 127.0.0.1:5984
      username: ""
      password: ""
      maxRetries: 3
      maxRetriesOnStartup: 10
      requestTimeout: 35s
      queryLimit: 10000
      maxBatchUpdateSize: 1000
      warmIndexesAfterNBlocks: 1

operations:
  listenAddress: 0.0.0.0:9443
  tls:
    enabled: false
    cert:
      file: /Users/joe/hartley-fabric/network/crypto-config/peerOrganizations/hartley.example.com/peers/peer0.hartley.example.com/tls/server.crt
    key:
      file: /Users/joe/hartley-fabric/network/crypto-config/peerOrganizations/hartley.example.com/peers/peer0.hartley.example.com/tls/server.key
    clientAuthRequired: false
    clientRootCAs:
      files:
        - /Users/joe/hartley-fabric/network/crypto-config/peerOrganizations/hartley.example.com/peers/peer0.hartley.example.com/tls/ca.crt

metrics:
  provider: disabled
  statsd:
    network: udp
    address: 127.0.0.1:8125
    writeInterval: 10s
    prefix: peer

mspConfigPath: /Users/joe/hartley-fabric/network/crypto-config/peerOrganizations/hartley.example.com/peers/peer0.hartley.example.com/msp
localMspId: HartleyMSPID
MSP:
    Version: 1.0
    CryptoConfig:
      Path: /opt/gopath/src/github.com/hyperledger/fabric/peer/crypto-config
    Identity:
      PrivateKey:
        Path: /opt/gopath/src/github.com/hyperledger/fabric/peer/crypto-config/peerOrganizations/org1.example.com/users/Admin@org1.example.com/msp/keystore/priv_sk
      Certificate: /opt/gopath/src/github.com/hyperledger/fabric/peer/crypto-config/peerOrganizations/org1.example.com/users/Admin@org1.example.com/msp/signcerts/Admin@org1.example.com-cert.pem

