OrdererOrgs:
  - Name: OrdererOrg
    Domain: hartley.example.com
    Specs:
      - Hostname: orderer
    MSPDir: /Users/joe/hartley-fabric/network/config/crypto-config/ordererOrganizations/hartley.example.com/orderers/orderer.hartley.example.com/msp

PeerOrgs:
  - Name: HartleyMSP
    Domain: hartley.example.com
    EnableNodeOUs: true
    Template:
      Count: 1
    Users:
      Count: 1
