OrdererOrgs:
  - Name: OrdererOrg
    Domain: hartley.example.com
    Specs:
      - Hostname: orderer

PeerOrgs:
  - Name: HartleyMSP
    Domain: hartley.example.com
    EnableNodeOUs: true
    Template:
      Count: 1
    Users:
      Count: 1
